spring.application.name=meu-primeiro-projeto

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/supermarket
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration