CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255)
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    telefone VARCHAR(255)
);

CREATE TABLE fornecedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR(255),
    ativo BOOLEAN NOT NULL,
    telefone VARCHAR(255),
    nome VARCHAR(255),
    CONSTRAINT uk_fornecedor_cnpj UNIQUE (cnpj)
);

CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL,
    nome VARCHAR(255),
    preco NUMERIC(10, 2),
    descricao VARCHAR(255),
    quantidade_estoque INTEGER,
    data_cadastro TIMESTAMP(6),
    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id)
);

CREATE TABLE carrinho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    CONSTRAINT uk_carrinho_cliente UNIQUE (cliente_id),
    CONSTRAINT fk_carrinho_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES cliente(id)
);

CREATE TABLE compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id BIGINT NOT NULL,
    data_compra TIMESTAMP(6),
    valor_total NUMERIC(10, 2),
    CONSTRAINT fk_compra_fornecedor
        FOREIGN KEY (fornecedor_id)
        REFERENCES fornecedor(id)
);

CREATE TABLE venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT,
    data_venda TIMESTAMP(6),
    valor_total NUMERIC(10, 2),
    CONSTRAINT fk_venda_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES cliente(id)
);

CREATE TABLE item_carrinho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrinho_id BIGINT,
    produto_id BIGINT,
    quantidade INTEGER,
    preco_unitario NUMERIC(10, 2),
    subtotal NUMERIC(10, 2),
    CONSTRAINT fk_item_carrinho_carrinho
        FOREIGN KEY (carrinho_id)
        REFERENCES carrinho(id),
    CONSTRAINT fk_item_carrinho_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id)
);

CREATE TABLE item_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    compra_id BIGINT NOT NULL,
    quantidade INTEGER,
    preco_compra NUMERIC(10, 2),
    subtotal NUMERIC(10, 2),
    CONSTRAINT fk_item_compra_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id),
    CONSTRAINT fk_item_compra_compra
        FOREIGN KEY (compra_id)
        REFERENCES compra(id)
);

CREATE TABLE item_venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT,
    venda_id BIGINT,
    quantidade INTEGER,
    preco_unitario NUMERIC(10, 2),
    subtotal NUMERIC(10, 2),
    CONSTRAINT fk_item_venda_produto
        FOREIGN KEY (produto_id)
        REFERENCES produto(id),
    CONSTRAINT fk_item_venda_venda
        FOREIGN KEY (venda_id)
        REFERENCES venda(id)
);