name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Executar testes e gerar cobertura
        run: ./mvnw clean verify

      - name: Analisar com SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw sonar:sonar -Dsonar.organization=kelwin-feitosa -Dsonar.token=$SONAR_TOKEN