name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          # As credenciais e nome do banco são intencionais, usado para teste
          POSTGRES_DB: supermarket
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d supermarket"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Verificar PostgreSQL
        run: |
          pg_isready -h localhost -p 5433 -U postgres -d supermarket

      - name: Executar testes e gerar cobertura
        run: ./mvnw clean verify
      - name: Executar testes e gerar cobertura
        run: ./mvnw clean verify

      - name: Verificar relatório JaCoCo
        run: |
          ls -lh target/site/jacoco/
          test -f target/site/jacoco/jacoco.xml

      - name: Analisar com SonarCloud
        if: github.event_name == 'push'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw sonar:sonar -Dsonar.token=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml